import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "A Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav className="p-6 bg-gray-800 text-white flex justify-between">
            <div className="font-bold">An Introductory Next App</div>
            <div className="space-x-4">
              <Link href="/" className="hover:underline">Home</Link>
              <Link href="/about" className="hover:underline">Server</Link>
              <Link href="/contact" className="hover:underline">Client</Link>
              <Link href="/users" className="hover:underline">Users</Link>
              <Link href="/users/friends" className="hover:underline">Friends</Link>
            </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
